### ISSUE TITLE
gsl_multimin example leads to compile errors

### ISSUE THREAD

**Issue by VoodooChild83** [twiecki/CythonGSL#27]
There seems to be a problem with the example provided in the multidimensional minimisation routine example: the compiler does not recognise any of the gsl_multimin_.... type identifiers, starting with the one below.

cdef const gsl_multimin_fdfminimizer_type* T

Is there a problem with the use of const? (I am using Cython 0.25.2)

Output:
Error compiling Cython file:
------------------------------------------------------------
...
def main_fdf():
    cdef size_t iter = 0
    cdef int max_iter = 100
    cdef int status

    cdef const gsl_multimin_fdfminimizer_type* T
              ^
------------------------------------------------------------

/Users/idiosyncrasy58/.ipython/cython/_cython_magic_8bae89fb4fa0616d795da00f11d03362.pyx:32:15: 'gsl_multimin_fdfminimizer_type' is not a type identifier

**Comment by VoodooChild83** [comment]
I have attempted to program a different example for an econometrics exercise and I am continuously obtaining errors concerning the type identifiers not being recognised by Cython. I'm wondering if this is an inherent bug or if it is a specific installation problem on my part.

**Comment by VoodooChild83** [comment]
I went back to the site-packages to check if the gsl_multimin.pxd file was even present. It turns out that there if CythonGSL is installed via PyPI not all the files will be included. I reinstalled directly from here and at least Cython compiles. Perhaps this issue should be checked out, especially if others are getting this from PyPI.

**Comment by molpopgen** [comment]
I just took a peek, and (as far as I can tell) it looks like the PyPi package pre-dates the addition of this particular .pxd file by about a year.  It is likely time for a new release to get the PyPi version in sync.

@twiecki -- thoughts?

**Comment by twiecki** [comment]
@molpopgen I uploaded 0.2.2 to pypi, can you try installing agian?

**Comment by VoodooChild83** [comment]
I was able to reinstall via PyPI. It downloaded all the files and recompiling with cython worked. (P.S. sorry for closing and commenting, that was a mistake).

**Comment by twiecki** [comment]
So this can't be closed?

**Comment by VoodooChild83** [comment]
I believe so. Thanks!

**Comment by VoodooChild83** [comment]
Yes. Believe it can be closed, the issue seems solved.
